# https://taskfile.dev
version: '3'

vars:
  BINFILE: k8see-exporter
  IMG: ghcr.io/sgaunet/k8see-exporter:latest

includes:
  dev: ./Taskfile_dev.yml

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  lint:
    desc: "Run linters"
    cmds:
      - golangci-lint run

  build:
    desc: "Build the binary"
    cmds:
      - CGO_ENABLED=0 go build .

  image:
    desc: "Build and push the image"
    deps: 
    - snapshot
    cmds:
      - docker tag ghcr.io/sgaunet/k8see-exporter:latest-amd64 {{.IMG}}
      - docker push {{.IMG}}

  snapshot:
    desc: "Create a snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser release --clean

  test:
    desc: "Run unit tests with race detection"
    cmds:
      - go test -v -race ./...

  test-coverage:
    desc: "Run tests and generate coverage report"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - sed -i.bak '/cmd/d' coverage.out && rm coverage.out.bak
      - go tool cover -func coverage.out | grep '^total:'
      - rm coverage.out
