# https://taskfile.dev
version: '3'

vars:
  BINFILE: k8see-exporter
  IMG: sgaunet/k8see-exporter:latest

tasks:
  default:
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  image:
    deps: 
    - default
    sources:
      - ./{{.BINFILE}}
      - Dockerfile
      - resources
    cmds:
      - docker build . -t {{.IMG}}
      - docker push {{.IMG}}

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser release --rm-dist --timeout 60m