---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8see-webui
  namespace: default
  annotations:
    kubernetes.io/change-cause: Creation
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8see-webui
  template:
    metadata:
      labels:
        app: k8see-webui
    spec:
      automountServiceAccountToken: false
      containers:
      - name: dashboard
        image: sgaunet/k8see-webui:latest
        ports:
        - containerPort: 8081
          name: http
        envFrom:
          - configMapRef:
              name: cm-k8see-webui

        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: k8see-webui
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "40Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "100m"
        imagePullPolicy: Always

      restartPolicy: Always

